pull_request_rules:
  - name: automatic merge
    conditions:
      - "status-success=ci/circleci: pep8"
      - "status-success=ci/circleci: py39"
      - "status-success=ci/circleci: py310"
      - "#approved-reviews-by>=1"
      - label!=work-in-progress
    actions:
      merge:
        strict: "smart"

  - name: automatic merge no review
    conditions:
      - "status-success=ci/circleci: pep8"
      - "status-success=ci/circleci: py39"
      - "status-success=ci/circleci: py310"
      - label!=work-in-progress
      - label=no-review-needed
    actions:
      merge:
        strict: "smart"

  - name: dismiss reviews
    conditions: []
    actions:
      dismiss_reviews: {}
